### PR TITLE
Fix compile error and add support for go modules

### PR DESCRIPTION
**Pull request by msimav**
-  `prometheus.Handler` is moved into `promhttp` package so the code is not compiling right now.

- _go.mod_ and _go.sum_ files added for reproducible build support

### CODE REVIEW

**Comment by pgporada** [comment]
Fixes #14

**Comment by pgporada** [comment]
@BartVerc Would you be able to take a look at this?

**Comment by pgporada** [comment]
For what it's worth I was able to successfully compile this just fine with golang 1.12.x just now. Perhaps prometheus fixed something upstream?

**Comment by Ivaylo-Korakov** [comment]
Hi,

Thank you very much for PR. Sorry for the late response. A colleague (@ThePib) of ours did the fix for this but forgot to take a look at the PRs first. Thanks for adding the go.mod.

**Comment by ThePib** [comment]
Whoops, sincerestest apologies :innocent:

**Pull request merged**
